name: 🎉 PR closed

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types:
      - closed

permissions:
  contents: read
  pull-requests: write

jobs:
  thank-you:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.user.login != 'renovate[bot]' }}

    steps:
      - name: 🙏 Post Thank You Comment
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          comment: |
            ## Merge Successful

            Thanks for your contribution! 🎉

            The changes will be part of the upcoming update of this plugin.
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.comment
            })
