on:
  workflow_call:
    inputs:
      run-on-windows:
        required: false
        type: boolean
        default: false

permissions: {}

jobs:
  test:
    name: 🧪 Tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ${{ inputs.run-on-windows && 'windows-latest' || '' }}
        exclude:
          - os: ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          # Download only the necessary files
          sparse-checkout: |
            src/
            tests/
            .gitignore
            bunup.config.ts
            package.json
            biome.jsonc
            bun.lock
            bunfig.toml
            cspell.yml
            tsconfig*.json
            !**/*.md
            tests/test-assets/*.md

      - name: 🔧 Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      # Run only on Windows because on Linux there are no problems with slow package installation
      - name: 📥 Cache Bun dependencies (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~\.bun
          key: ${{ matrix.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: ${{ matrix.os }}-bun-cache-

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile --prefer-offline --ignore-scripts

      - name: 🗞️ Lint
        run: bun run lint

      - name: 🗞️ Run Woke linter
        uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true

      - name: 🧪 Run tests
        run: bun run test
